kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-ms-pvc
  labels:
    app: postgres-ms
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi