apiVersion: v1
kind: Service
metadata:
  name: postgres-ms-service
  labels:
    app: postgres-ms
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
   app: postgres-ms