kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-ms-pv
  labels:
    type: local
    app: postgres-ms
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/ms