KEYCLOAK_SERVICE_HOST: localhost
KEYCLOAK_SERVICE_PORT: 9999
ZIPKIN_SERVICE_HOST: localhost

server:
  port: 8888

spring:
  autoconfigure:
    exclude: org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_SERVICE_HOST}:${KEYCLOAK_SERVICE_PORT}/auth/realms/playground/protocol/openid-connect/certs
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://${ZIPKIN_SERVICE_HOST}:9411/
  application:
    name: edge-service-zuul
  cloud:
    kubernetes:
      discovery:
        catalogServicesWatchDelay: 10000
zuul:
  debug:
    request: true
  sensitive-headers: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  include-debug-header: true
  ignored-services: keycloak-service, postgres-*, liquor-store-service, edge-service-zuul-service
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 20

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.netflix: DEBUG

