kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-kc-pv
  labels:
    type: local
    app: postgres-keycloak
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/keycloak