kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-kc-pvc
  labels:
    app: postgres-keycloak
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi