apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8082
  selector:
    app: analytics