apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      name: analytics
      labels:
        app: analytics
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
      - name: analytics
        image: henrj/analytics-service:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8082
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 40
          periodSeconds: 15
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongo-analytics-service
        - name: KEYCLOAK_SERVICE_HOST
          value: "192.168.99.100"
        - name: KEYCLOAK_SERVICE_PORT
          value: "30080"
        - name: KAFKA_URL
          value: kafka-service
        - name: ZIPKIN_SERVICE_HOST
          value: zipkin-service
          # Disable Eureka to make room for KubernetesDiscoveryClientAutoConfiguration
        - name: SPRING_AUTOCONFIGURE_EXCLUDE
          value: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi