apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8085
  selector:
    app: customer