kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-analytics-pv
  labels:
    type: local
    app: mongo-analytics
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/analytics