apiVersion: v1
kind: Service
metadata:
  name: mongo-analytics-service
  labels:
    app: mongo-analytics
spec:
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
   app: mongo-analytics