kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-analytics-pvc
  labels:
    app: mongo-analytics
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi