apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9092
      nodePort: 30092
  selector:
    app: kafka