apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      name: kafka
      labels:
        app: kafka
    spec:
      restartPolicy: Always
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9092
            protocol: TCP
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: DELETE_TOPIC_ENABLE
          value: "true"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi