apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ms-ingress
spec:
  rules:
  - host: ms.demo
    http:
      paths: 
      - path: /
        backend:
          serviceName: liquor-store-service
          servicePort: 8081
      - path: /zipkin
        backend:
          serviceName: zipkin-service
          servicePort: 9411