apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-zuul
  labels:
    app: edge-service-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service-zuul
  template:
    metadata:
      name: edge-service-zuul
      labels:
        app: edge-service-zuul
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
      - name: edge-service-zuul
        image: henrj/edge-service-zuul:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
          - containerPort: 8888
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 25
          periodSeconds: 20
        env:
        - name: KEYCLOAK_SERVICE_HOST
          value: "192.168.99.100"
        - name: KEYCLOAK_SERVICE_PORT
          value: "30080"
        - name: ZIPKIN_SERVICE_HOST
          value: zipkin-service
          # Disable Eureka to make room for KubernetesDiscoveryClientAutoConfiguration
        - name: SPRING_AUTOCONFIGURE_EXCLUDE
          value: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi