apiVersion: v1
kind: Service
metadata:
  name: liquor-store-service
  labels:
    app: liquor-store
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8081
      nodePort: 30081
  selector:
    app: liquor-store