DATABASE_HOST: localhost
KEYCLOAK_SERVICE_HOST: localhost
KEYCLOAK_SERVICE_PORT: 9999
EUREKA_SERVICE_HOST: localhost
ZIPKIN_SERVICE_HOST: localhost

server:
  port: 8083

spring:
  application:
    name: beer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVICE_HOST}:${KEYCLOAK_SERVICE_PORT}/auth/realms/playground
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://${ZIPKIN_SERVICE_HOST}:9411/
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/ms
    username: springuser
    password: password
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
    type: org.postgresql.ds.PGPoolingDataSource
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    service-url:
      default-zone: http://${EUREKA_SERVICE_HOST}:8761/eureka
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.netflix: DEBUG
