KEYCLOAK_SERVICE_HOST: localhost
KEYCLOAK_SERVICE_PORT: 9999
ZIPKIN_SERVICE_HOST: localhost
KAFKA_URL: localhost:9092
spring:
  autoconfigure:
    exclude: org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration
  application:
    name: analytics-service
  data:
    mongodb:
      database: analytics
      username: springuser
      password: password
      host: localhost
      port: 27017
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVICE_HOST}:${KEYCLOAK_SERVICE_PORT}/auth/realms/playground
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://${ZIPKIN_SERVICE_HOST}:9411/
server:
  port: 8082
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.netflix: DEBUG
