apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      name: zipkin
      labels:
        app: zipkin
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9411
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9411
          initialDelaySeconds: 40
          periodSeconds: 15
        env:
        - name: DATABASE_HOST
          value: postgres-ms-service
        - name: KEYCLOAK_SERVICE_HOST
          value: "192.168.99.100"
        - name: KEYCLOAK_SERVICE_PORT
          value: "30080"
          # Disable Eureka to make room for KubernetesDiscoveryClientAutoConfiguration
        - name: SPRING_AUTOCONFIGURE_EXCLUDE
          value: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi