apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    app: zipkin
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9411
  selector:
    app: zipkin